modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="fightclass3"
    version="1.0.0"
    displayName="Fight Class 3"
    description="Fight Class 3 mod"

[[dependencies.fightclass3]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fightclass3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
